data:
  path: data/raw/injury.csv
  #id_col: subject_id
  time_col: afchnge          # required for did; omit for cross-sectional designs

outcome: ldurat
treatment: highearn
covariates:
  - male
  - married
  - hosp
  - indust
  - injtype
  - age
  - prewage
  - totmed
  - benefit
  - head
  - neck
  - upextr
  - trunk
  - lowback
  - lowextr
  - occdis
  - manuf
  - construc
  - lage



methods:
  - psm
  - did
  - drdid
  #- iv
  #- rdd
  #- fixed_effects
  - aipw

sensitivity: true

agent:
  interpret: true
